version: '3.1'


services:
  mysql:
    image: mysql:8.0
    container_name: mysql-database
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: my_user
      MYSQL_PASSWORD: my_password
      
  zookeeper:
    image: zookeeper
    ports:
      - "2181:2181"
  
  kafka:
    image: apache/kafka
    container_name: kafka
    ports:
      - "9092:9092"
    environment:
      - "KAFKA_ADVERTISED_HOST_NAME: localhost"
      - "KAFKA_ZOOKEEPER_CONNECT : zookeeper:2181" 